apis/directions.ts
app/about/directions/page.tsx
app/about/student-clubs/page.tsx
app/community/news/page.tsx
app/community/notice/[id]/page.tsx
app/community/notice/page.tsx
components/directions/DirectionList.tsx
components/directions/LocationGuide.tsx
components/directions/LocationInformation.tsx
components/directions/LocationMap.tsx
types/directions.ts

- 찾아오는 길 추가
- 카카오맵 api 사용
- `DirectionsPage`
- 찾아오는 길 페이지를 추가했습니다.
- 별거 없습니다.
- 동아리와 동일하게, 찾아오는 길에 대한 설명 서버에서 전부 불러와서 프론트단에서 그냥 필터링하는 구조입니다. 어차피 3개밖에 없으니 별 문제는 없을 듯합니다.
- 탭(대중교통, 승용차, 지방 및 해외)이 지도 밑에 있으니 다른 탭 눌렀을 때 스크롤 위치가 유지되도록 하고 싶었는데, 왜인지 `<Link scroll={false}>`가 안 먹혀서 일단 페이지 바뀔 때마다 맨 위로 자동 스크롤되는 상황입니다. 사용자가 조금 불편하긴 하겠지만 당장에 고쳐야 할 큰 이슈는 아니니, 방법을 찾게 된다면 수정하도록 하겠습니다.😢
- 여기까지는 api 요청에 axios 썼는데, fetch 알아보고 다른 pr에서 몰래 같이 바꿔놓겠습니다.🤣
- `LocationMap`
- 여기도 `useEffect` 썼는데, `useSWR` 좀 알아보고 다른 pr에서 같이 바꿔놓을게요!
- api 쓰려면 키를 발급받아야 해서, 일단 제 이름으로 받았습니다. 이거 어떻게 할지는 나중에 생각해봐도 될 것 같습니다.
- 위에서 말한 키를 코드에 그대로 넣으면 보안상 문제가 생길 수도 있을 것 같아서, `.env.local` 만들고 넣어두었습니다. 이건 gitignore에 있는 파일이라 깃허브에 안 올라갔을 거예요.
- 페이지 이름이 `directions`라서 대중교통, 승용차 이런 것들 명칭도 `direction`으로 해놓긴 했는데 뭔가... 어색함... 굳이 의미를 끼워 맞추자면 합리화할 수는 있겠으나 …

✨ 찾아오는 길 추가

---

apis/contact.ts
apis/facilities.ts
apis/seminar.ts
app/about/contact/page.tsx
types/contact.ts
types/facilities.ts
types/post.ts

- 현재 연락처 페이지의 세부 사항들을 따로 받는 형태라 HtmlViewer로 하지 않고 각각의 데이터들을 받아놓는 형식으로 하였습니다.
- 크게 특별한 점은 없어서 간단하게 리뷰 후에 머지해도 괜찮을 것 같습니다.

✨ 연락처 페이지 추가

---

apis/topConferenceList.ts
app/research/top-conference-list/page.tsx
components/research/topConferenceList/ConferenceListTable.tsx
types/research.ts
utils/formatting.ts

- 줄이 2줄일 경우 크기를 늘리기 위해 Table형태로 하기 보다 그냥 flex box로 표 내용을 만들었습니다.
- 크게 특별한 부분은 없어 간단하게 리뷰후 머지해도 좋을 것 같습니다.

✨ Top Conference List 페이지 추가

---

components/common/HTMLViewer.tsx

Suneditor 리드미의 아래 내용을 참고하여 적용
> When you display a document created by suneditor
You need to include "src/assets/css/suneditor-contents.css" or "dist/css/suneditor.min.css" file.
Then add "sun-editor-editable" to the class name of the Tag element that displays the content.
If you are using RTL mode, you also need to add "se-rtl".
In "suneditor-contents.css", you can define the style of all the tags created in suneditor.
community/news/create/page.tsx를 아래 내용으로 수정하면 '게시하기' 버튼을 누를때마다 하단에 HTMLViewer의 내용이 업데이트됨. 
```tsx
'use client';
import { useState } from 'react';
import HTMLViewer from '@/components/common/HTMLViewer';
import PostEditor from '@/components/editor/PostEditor';
import { EditorContent } from '@/components/editor/PostEditorProp';
import PageLayout from …
```

💄 HTMLViewer에 suneditor 스타일 적용

---

app/[locale]/academics/graduate/course-changes/page.tsx
app/[locale]/academics/undergraduate/course-changes/page.tsx

- 교과목 변경내역 GET 함수에 인자를 전달하지 않아서 발생했던 버그(자동으로 대학원 변경내역만 보여짐) 수정

🩹 교과목 변경내역 인자 전달 오류 수정

---

app/[locale]/academics/graduate/courses/page.tsx
app/[locale]/content.tsx
app/[locale]/page.tsx
components/academics/CourseCards.tsx
components/academics/CourseDetailModal.tsx
components/academics/CourseList.tsx
components/academics/CourseListHeader.tsx
components/academics/CourseListRow.tsx
components/academics/CoursePageContent.tsx
components/academics/CourseRow.tsx
components/layout/header/Header.tsx
components/layout/pageLayout/MajorCategoryPageLayout.tsx
components/layout/pageLayout/PageLayout.tsx
components/layout/pageLayout/PageTitle.tsx
components/layout/pageLayout/SubNavbar.tsx
components/main/MainPageContent.tsx
components/research/groups/ResearchGroupDetails.tsx
components/research/groups/ResearchGroupsPageContent.tsx

- 헤더가 본문과 함께 스크롤되도록 수정
- 통합검색 페이지는 `use client` 새로 필요해서 일단 안 건드림. 통합검색 마저 만들 때 @Yeolyi가 해주시면 감사하겠습니다
- 메인은 뭐가 어떻게 될지 몰라서 기존 코드 삭제하지는 않고 주석처리만 해둠

💄 헤더 페이지 레이아웃에 통합

---

app/[locale]/research/labs/ResearchLabDetails.tsx
app/[locale]/research/labs/[id]/ResearchLabDetails.tsx
app/[locale]/research/labs/[id]/page.tsx

- `useReponsive` 훅 사용한 파일이 서버 컴포넌트로 되어 있어서 발생했던 에러 해결

🐛 연구실 페이지 클라이언트 컴포넌트 에러 해결

---

app/[locale]/research/labs/[id]/ResesarchLabInfo.tsx
app/[locale]/search/CommunitySection.tsx
app/[locale]/search/MemberSection.tsx
app/[locale]/search/helper/BasicRow.tsx
app/[locale]/search/helper/NewsRow.tsx
app/[locale]/search/helper/Section.tsx
app/[locale]/search/page.tsx
components/common/RangeBolded.tsx
styles/globals.css

- 검색 결과 본문 말줄임 클래스 추가
- tailwind에서 제공하는 `truncate`를 사용하려고 했으나, 기본 2줄 말줄임 적용 시에 활성화되는 다른 클래스들도 직접 리셋해주기 위해 한 줄 말줄임도 `truncate-single` 클래스 새롭게 추가하여 사용
- 새소식, 교수진 레이아웃 정도만 수정
- 기타 gap 등 미세 조정

📱 통합검색 반응형

---

app/[locale]/people/faculty/[id]/page.tsx

- `/faculty`에서 명예교수를 불러왔을 때는 404 페이지로 이동

🐛 명예교수가 교수진 개별 페이지에 보이는 버그 수정

---

app/[locale]/about/directions/page.tsx
app/[locale]/about/student-clubs/page.tsx
app/[locale]/admin/page.tsx
app/[locale]/research/centers/page.tsx
app/[locale]/research/groups/page.tsx
app/[locale]/reservations/introduction/page.tsx
components/common/selection/SelectionList.tsx
types/about.ts
utils/findSelectedItem.ts

- 영문명이 존재하는 경우 선택형 쿼리에서 영어 사용 (예시: 동아리 소개 페이지)
- `Direction` type에서 `engName` 삭제
- 실제 백엔드 응답 중 해당 속성이 없음

♻️ 선택형 쿼리 영어로 올라가도록 변경

---

app/[locale]/community/news/[id]/edit/EditNewsPageContent.tsx
app/[locale]/community/news/create/page.tsx
app/[locale]/community/notice/[id]/edit/EditNoticePageContent.tsx
app/[locale]/community/notice/create/page.tsx
app/[locale]/community/seminar/[id]/edit/EditSeminarPageContent.tsx
app/[locale]/community/seminar/create/page.tsx
components/layout/pageLayout/PageLayout.tsx

- 공지/새소식/세미나 추가 및 편집 페이지에서 서브내비 숨김

🩹 소식 편집 페이지에서 서브내비 제거

---

app/[locale]/community/news/helper/NewsRow.tsx
app/[locale]/community/notice/helper/NoticeListRow.tsx
app/[locale]/community/seminar/helper/SeminarRow.tsx
components/post/PaginatedLink.tsx
components/post/PostFooter.tsx

page.tsx에서 searchParams로 받아 아래로 넘겨주기에는 prop drilling이 심한 것 같아 Link쪽만 client component로 바꿔줬습니다.
`PaginatedLink`는 현재 페이지의 search param에 pageNum이 있다면 본인의 `href`의 뒤에 pageNum을 붙입니다. 
링크 컴포넌트 더 나은 이름 추천받음..

✨ 소식 탭 목록 버튼을 누르면 원래 있던 목록으로 이동

---

app/[locale]/community/news/page.tsx
app/[locale]/community/notice/page.tsx
app/[locale]/community/seminar/SeminarContent.tsx
utils/validatePageNum.ts
utils/validateSearchParams.ts

- 소식탭 공지와 새소식 태그에서 나오던 500 에러 태그 validation 추가해서 수정
- `validatePageNum` 파일명 `validateSearchParams`로 변경

🔒️ 정수 오버플로우 수정

---

actions/people.ts
actions/session.ts
apis/common.ts
apis/index.ts
apis/people.ts
app/[locale]/people/staff/[id]/StaffMemberPageContent.tsx
app/[locale]/people/staff/[id]/edit/StaffEditPageContent.tsx
app/[locale]/people/staff/[id]/edit/page.tsx
app/[locale]/people/staff/[id]/page.tsx
app/[locale]/people/staff/create/page.tsx
app/[locale]/people/staff/page.tsx
components/common/Buttons.tsx
components/common/ImageWithFallback.tsx
components/editor/FacultyEditor.tsx
components/editor/StaffEditor.tsx
components/editor/common/ImagePicker.tsx
components/modal/AlertModal.tsx
middleware.ts
types/language.ts
types/people.ts
utils/formValidation.ts
utils/hooks/useEditorContent.ts

- 행정직원 편집 기능 구현
- `BASE_URL`을 `/api/v2`로 사용해야 해서 단순히 get, put, post, delete 메소드를 하나씩 더 만듦. 기존 함수에 파라미터 받아서 base url 구분할 수도 있지만 편집 기능 작업 끝내면 url은 다시 하나로 합쳐질 거라 기존 함수 수정하지 않고 새로 만듦.
- `ImagePicker`에 기존 사진 삭제 기능 추가
- 편집용 페이지 `/create`, `/edit`은 전부 auth 필요하도록 middleware 로직 수정
- 전에 `setContentByKey` 공통으로 빼려고 만들었던 `useEditorContent` 훅에서 한영 데이터와 한글만 있는 데이터 모두 사용 가능하도록 함수 오버로딩 사용하여 리팩토링

✨ 행정직원 추가/수정/삭제 기능

---

actions/about.ts
apis/about.ts
app/[locale]/about/directions/DirectionsDetails.tsx
app/[locale]/about/directions/edit/DirectionsEditPageContent.tsx
app/[locale]/about/directions/edit/page.tsx
app/[locale]/about/directions/page.tsx
app/[locale]/about/facilities/edit/FacilitiesEditPageContent.tsx
app/[locale]/about/facilities/edit/page.tsx
app/[locale]/about/facilities/page.tsx
app/[locale]/about/future-careers/CareerCompanies.tsx
app/[locale]/about/future-careers/CareerStat.tsx
app/[locale]/about/future-careers/description/edit/CareerDescriptionEditContent.tsx
app/[locale]/about/future-careers/description/edit/page.tsx
app/[locale]/about/future-careers/page.tsx
app/[locale]/about/future-careers/stat/create/page.tsx
app/[locale]/about/future-careers/stat/edit/CareerStatEditPageContent.tsx
app/[locale]/about/future-careers/stat/edit/page.tsx
app/[locale]/academics/helper/timeline/TimelineEditor.tsx
components/common/Buttons.tsx
components/editor/CareerStatEditor.tsx
components/editor/common/ActionButtons.tsx
components/editor/common/BasicTextInput.tsx
components/modal/AlertModal.tsx
constants/network.ts
types/about.ts
utils/formValidation.ts
utils/number.ts

- 시설 안내 수정 기능 추가
- 찾아오는 길 수정/삭제 기능 추가
- 졸업생 진로 편집 기능 추가
- 본문 수정
- 진로 현황 추가/수정
- 창업 기업 추가/수정/삭제
- 전반적인 로직은 다른 페이지들 편집과 유사함
- 찾아오는 길 제목 하드코딩되어 있던 것(대중교통'으로', 승용차'로', 해외'에서') 제거하고 제목 키워드만 담는 것으로 변경
- 영문까지 고려할 방법이 마땅치 않았음

✨ 시설 안내, 찾아오는 길, 졸업생 진로 현황 편집 기능

---

actions/academics.ts
components/common/Attachments.tsx
utils/formData.ts

질문있습니다
`decodeFormDataFileName(formData, 'newAttachments')` 이거 하면 formData 내부의 첨부파일명이 바뀌는 건가?
이걸 `action` 메소드에서 실행하는 거랑 그 이전에 다른 컴포넌트에서 실행하는 거랑 어떤 차이가 있는 건가요,,,

🐛 학사 및 교과 action 요청할 때 디코딩 추가

---

apis/v2/academics/scholarship/index.ts
app/[locale]/people/components/PeopleCell.tsx
app/[locale]/people/components/ProfileImage.tsx
app/[locale]/people/components/style.module.css
app/[locale]/search/MemberSection.tsx
app/[locale]/search/style.module.css
components/common/ImageWithFallback.tsx
components/form/Date.tsx
components/form/html/HTMLEditor.tsx
components/form/html/HTMLHydrator.tsx
components/form/html/HTMLViewer.tsx
components/form/html/TopRightImage.tsx
eslint.config.mjs
middleware.ts
package-lock.json
package.json
public/image/calendar.svg
public/image/distance.svg
public/image/header/menu.svg
public/image/person.svg

- Link, Image등의 컴포넌트에서 style prop 금지
- HTMLViewer의 CSP 대응
- (PR과는 무관하지만) no-unused-vars 추가
브라우저에서 Raw HTML을 렌더링할 때 style 속성이 포함되어있으면 CSP 관련 에러가 발생합니다. 따라서 서버단에서는 html-react-parser를 사용해 style 속성을 제거해 data-style 속성에 백업해두고, 브라우저에서는 useLayoutEffect에서 data-style을 style로 복구시킵니다.
새소식 등 게시물 볼 때 에러 미발생. 
https://github.com/remarkablemark/html-react-parser

🔒️ HTMLViewer의 CSP 문제 수정

---

actions/admissions.ts
apis/v2/admissions/[mainType]/[postType].ts
apis/v2/admissions/graduate/regular-admission.ts
apis/v2/admissions/international/exchange-visiting.ts
apis/v2/admissions/international/graduate.ts
apis/v2/admissions/international/scholarships.ts
apis/v2/admissions/international/undergraduate.ts
apis/v2/admissions/undergraduate/early-admission.ts
apis/v2/admissions/undergraduate/regular-admission.ts
app/[locale]/admissions/components/AdmissionsEditor.tsx
app/[locale]/admissions/components/AdmissionsPageContent.tsx
app/[locale]/admissions/graduate/regular-admission/edit/page.tsx
app/[locale]/admissions/graduate/regular-admission/page.tsx
app/[locale]/admissions/international/exchange/edit/page.tsx
app/[locale]/admissions/international/exchange/page.tsx
app/[locale]/admissions/international/graduate/edit/page.tsx
app/[locale]/admissions/international/graduate/page.tsx
app/[locale]/admissions/international/scholarships/edit/page.tsx
app/[locale]/admissions/international/scholarships/page.tsx
app/[locale]/admissions/international/undergraduate/edit/page.tsx
app/[locale]/admissions/international/undergraduate/page.tsx
app/[locale]/admissions/page.tsx
app/[locale]/admissions/undergraduate/early-admission/edit/page.tsx
app/[locale]/admissions/undergraduate/early-admission/page.tsx
app/[locale]/admissions/undergraduate/regular-admission/edit/page.tsx
app/[locale]/admissions/undergraduate/regular-admission/page.tsx
constants/network.ts

- 입학 하위 페이지들 편집 기능 추가
- `AdmissionEditor` 구현
- 입학 공용 GET, PUT api 생성
- 개별 api 제거
- 영문버전으로 전환했더니 description에 `<html> ...` 처럼 되어 있어서 에러 발생. 편집 기능 사용하여 정상적인 description으로 데이터 변경해서 해결.
- 입학탭 하위 페이지들의 편집 기능 작동 확인
- 한영 변환 시 html 중복 마운팅 에러 없는지 확인
.

✨ 입학탭 편집 기능

---

app/[locale]/community/council/page.tsx
components/layout/pageLayout/MajorCategoryPageLayout.tsx

- 학생회 중분류 페이지 추가
- 기존 대분류 페이지 컴포넌트 그대로 사용
- 대분류 페이지에 라이트 모드 추가
- 학생회 페이지는 라이트 모드, 그 이외 대분류 페이지들은 기존의 다크 모드를 유지하고 있어야 함
.

✨ 학생회 중분류 페이지 추가

---

actions/council.ts
apis/v2/council/report/index.ts
app/[locale]/community/council/report/[id]/page.tsx
app/[locale]/community/council/report/assets/NaviBar_Close.svg
app/[locale]/community/council/report/create/page.tsx
app/[locale]/community/council/report/page.tsx
constants/segmentNode.ts

- 활동 보고 목록 페이지 구현
- 디버깅용 활동 보고 상세 페이지 구현
특정 페이지에서 사용되는 에셋은 해당 페이지 디랙토리의 `assets` 폴더에서 관리합니다. 
활동 보고 목록 페이지 진입
- 로그인시 새 게시물 버튼 표시 및 동작 확인
- 타일 호버시 활동 보고 정보가 뜨는지 확인
- 타일 클릭시 활동 보고 페이지 이동 확인

✨ 활동보고 목록 페이지 구현

---

apis/types/council.ts
apis/v2/council/report/[id].ts
app/[locale]/community/components/PostFooter.tsx
app/[locale]/community/council/report/[id]/page.tsx
lint-staged.config.js

- PostFooter에 CouncilReport 지원 추가
- CouncilReportPage 구현 
lint-staged에서 tsc로 타입 검사할 때 .next 폴더를 검사하는 이슈가 있어 공식 문서 참고해 `-p tsconfig.json` 플래그 추가함. tsconfig에 include를 보고 거기만 검사하지 않을까... 예상중. 
api에서 500이 내려와 임시로 목데이터 사용중. 
활동 보고 상세 페이지 진입해 아래 확인
- 내용 잘 뜨는지
- 번역 잘 되는지
- 편집, 삭제 버튼 잘 되는지
- 이전글 다음글 잘 가는지
https://github.com/lint-staged/lint-staged?tab=readme-ov-file#example-run-tsc-on-changes-to-typescript-files-but-do-not-pass-any-filename-arguments

✨ 활동 보고 뷰어 구현

---

actions/council.ts
apis/types/council.ts
apis/v2/council/report/[id].ts
app/[locale]/community/components/PostDeleteButton.tsx
app/[locale]/community/components/PostFooter.tsx
app/[locale]/community/council/report/[id]/edit/client.tsx
app/[locale]/community/council/report/[id]/edit/page.tsx
app/[locale]/community/council/report/[id]/page.tsx
app/[locale]/community/council/report/components/CouncilReportEditor.tsx
app/[locale]/community/council/report/page.tsx
app/[locale]/people/staff/[id]/page.tsx
middleware.ts

활동보고 편집 관련 api, server action, 에디터 컴포넌트 구현
활동보고 페이지가 추가되면서 PostFooter 컴포넌트도 수정이 필요했는데, 바람직한 상황이라고는 생각되지 않아 https://github.com/wafflestudio/csereal-web/issues/322 에서 리팩터링해보겠습니닷.
학생회 권한관련 사항을 middleware에 반영합니다. 
학생회 권한 로그인 후 편집/삭제 기능이 동작하는지 확인

✨ 학생회 활동보고 편집 페이지 구현

---

app/[locale]/community/council/page.tsx
components/layout/pageLayout/CategoryGrid.tsx
components/layout/pageLayout/MajorCategoryPageLayout.tsx
components/layout/pageLayout/SubNavbar.tsx
utils/page.ts

- 학생회 중분류 페이지 헤더 작게 변경
- 서브내비에서 학생회 하위탭은 보이지 않도록 처리
- `MajorCategoryPageLayout` 컴포넌트에서 타이틀 컴포넌트 별도로 받을 수 있도록 확장
- 서브내비 컴포넌트에서 학생회 하위탭 분기처리
- `SegmentNode`의 `children` 속성이 필수이므로 `getAllSubTabs`의 첫번째 줄은 의미 없는 코드가 되어 제거

💄 학생회 UI qa 반영

---

app/[locale]/community/council/report/components/CouncilReportEditor.tsx
app/[locale]/community/council/report/page.tsx
app/[locale]/community/council/rules/page.tsx

- 학생회칙 및 세칙 페이지 소제목 (학생회칙, 세칙) 폰트 크기 20->18
- 활동 보고 페이지 맥북 13인치에선 3열로 보이는데 4열로 보이도록 대응 - 활동 보고 페이지 각 썸네일 호버 시 문구 타이틀 20->18, 학생회 및 날짜 12->13으로 수정
- 활동 보고 페이지 새 게시물 작성 시 게시자에 제 n대 학생회~~ 쓰는 란 placeholder 제거

🐛 학생회칙, 활동보고 QA 반영

---

components/layout/navbar/NavbarDetail.tsx

학생회 하위 탭에서 Navbar에 highlight 정상적으로 표시
```
highlight={curNode === node || curNode.parent === node}
```
로 고쳤습니다.

🐛 학생회 하위탭 내브바에서 하이라이트 표시 안 됨 고침

---

components/form/html/HTMLViewer.tsx

게시물 내에서 이미지가 레이아웃 크기에 반응하지 않는 문제 수정
./components/form/html/HTMLViewer.tsx 에서 HTML 내용을 파싱할 때 쓰이는 replace 함수를 수정.  
img 태그일 경우 style 속성에   
max-width:100%; height:auto;   -> max-width 스타일은 굳이 없어도 되어서 제거했습니다.
을 추가합니다.

🐛 게시물 내 HTML 내용 중 이미지 비율 깨짐 문제 수정

---

app/[locale]/academics/components/timeline/Timeline.tsx
app/[locale]/academics/components/timeline/TimelineViewer.tsx
app/[locale]/community/council/meeting-minute/CouncilMeetingMinuteEditor.tsx
app/[locale]/community/council/meeting-minute/MinutePageContent.tsx
app/[locale]/community/council/meeting-minute/create/client.tsx
app/[locale]/community/council/meeting-minute/create/page.tsx
app/[locale]/community/council/meeting-minute/edit/EditMinutePageContent.tsx
components/common/Timeline.tsx

- 연도 추가 안 되던 것 수정
- 회의록 추가/편집 시 첨부파일 필수로 지정
- 회의록 차수 내림차순 정렬, 추가 버튼 위로 이동
- 특정 연도 하위에 회의록 추가 시 연도와 차수는 이미 정해져 있으므로 페이지 제목에 넣고, 에디터 본문에서는 첨부파일만 편집
- 타임라인 마지막 down arrow 제거

🐛 회의록 qa 반영

---

app/.internal/components/InternalEditor.tsx

internal edit 에서 취소 버튼을 누르면 /.internal/.internal 로 이동되던 걸 수정했습니다.

🐛 internal cancel 버튼의 리다이렉트 경로 앞에 / 추가

---

app/[locale]/community/council/client.tsx
app/[locale]/community/council/page.tsx
components/layout/pageLayout/SubNavbar.tsx
constants/segmentNode.ts

- 학생회 관련 페이지에 있을 때만 학생회 하위탭들 전부 서브내비에 표시
- 소식 내 다른 페이지에서는 `학생회`탭만 표시
- `TreeNode` 불필요한 것 같아 `SegmentNode`로 대체
#328

🐛 학생회탭 서브내비 처리

---

apis/types/council.ts
app/[locale]/community/components/PostDeleteButton.tsx
app/[locale]/community/components/PostFooter.tsx
app/[locale]/community/council/report/[id]/page.tsx
app/[locale]/community/news/[id]/NewsViewer.tsx
app/[locale]/community/notice/[id]/NoticeViewer.tsx
app/[locale]/community/seminar/[id]/SeminarViewer.tsx
app/[locale]/community/seminar/[id]/page.tsx

https://github.com/wafflestudio/csereal-web/issues/322 에 적힌 이슈를 처리했습니다.
postType을 없애고, 각 상위 컴포넌트에서 해당하는 서버 액션과 경로를 직접 props로 보내서 postFooter에서 처리합니다.

♻️ postfooter에서 posttype props제거

---

app/[locale]/admin/helper/slide/SlideList.tsx
app/[locale]/reservations/[roomType]/[roomName]/helper/calendar/NavigateButtons.tsx

close #373 
이슈로 올라온 캘린더 바깥 클릭 시 달력 popover가 종료되도록 수정했습니다.
추가로 useClickOutside 훅은 우선 NavigationButton.tsx 안에 두었습니다. MuiCalender 외에는 이 훅을 사용할 일이 없어 보여서 따로 util로 빼지 않았는데, 더 좋은 방법이 있으면 추천해주세요~

🐛  세미나실 예약 페이지 중, 달력 바깥 클릭 시 달력창 종료

---

components/common/Buttons.tsx
components/form/Calendar.tsx
components/modal/AlertModal.tsx

에디터 작성 취소 모달이 나타났을 때, 기본 포커스를 모달창의 확인 버튼으로 둡니다.

🐛 에디터 작성 취소 버튼 눌렀을 때, 모달창 속 확인 버튼을 디폴트 포커스 값으로 지정

---

app/[locale]/community/seminar/[id]/edit/EditSeminarPageContent.tsx

close #
```
description: content.description || null,
introduction: content.description || null,
```
로 되어있어서 편집시 내용 오염이 발생했었네요.

🐛 세미나 편집시 description이 introduction에 유입되는 버그 픽스

---

app/[locale]/admin/helper/ListCell.tsx
app/[locale]/admin/helper/slide/SlideList.tsx
app/[locale]/community/council/report/page.tsx
app/[locale]/community/news/[id]/NewsViewer.tsx
app/[locale]/community/news/components/NewsRow.tsx
app/[locale]/community/notice/[id]/NoticeViewer.tsx
app/[locale]/community/notice/components/NoticeListRow.tsx
app/[locale]/community/seminar/components/SeminarRow.tsx
app/[locale]/components/NewsCard.tsx
app/[locale]/components/NoticeSection.tsx
utils/hooks/useDayjs.ts

close #369
```typescript
simple: {
ko: 'YYYY/M/DD',
en: 'YYYY/M/DD',
},
day: {
ko: 'YYYY/M/DD (ddd)',
en: 'YYYY/M/DD ddd',
},
time: {
ko: 'YYYY/M/DD (ddd) A hh:mm',
en: 'YYYY/M/DD ddd hh:mm A',
}
```
이슈에서 적어준 서식대로 반영해서 고쳤습니다.
고치는 건 다 고쳤는데, 이제보니까 작은 단위의 컴포넌트들 중, client와 server가 혼재된 경우도 있고, 'use client' directive 없이 선언된 client component가 상위 컴포넌트에서 선언된 'use client'로 암시적인 의존 관계도 있네요. 관련해서 next 공식 문서좀 읽다가 늦어졌습니다 😅. 이건 따로 이슈 올리겠습니다.
페이지 내에서 date가 표시되는 곳들이 locale 변경 시 따라서 잘 바뀌는지 테스트하기

♻️ 날짜 컨벤션 지정 및 레거시 formatDate 코드 정리

---

middleware.ts
utils/auth.ts

close #339
미들웨어에서 번잡하게 체크하던 페이지별 권한 함수를 정리하고 별도 파일로 분리합니다. 
기존 목표는 모든 페이지의 SegmentNode를 만들어 거기서 접근 가능한 페이지를 명시하는거였는데, 생성/편집페이지의 SegmentNode를 모두 만들어야하고 url에서 권한을 파악하는 지금 방식이 유효해보여 기존 방식에서 리팩터링만 진행했습니다.
권한별로 페이지 접근 가능한지 테스트

♻️ 페이지별 권한 처리 함수 리팩터링

---

app/[locale]/about/components/AboutEditor.tsx
components/form/Action.tsx
components/form/html/HTMLEditor.tsx

Form 에러 처리 방법을 수정합니다. 일단 소개탭 일부에만 적용했고 리뷰 완료되면 다른 에디터에도 적용하겠습니다.
에러 내용을 토스트 대신 텍스트로 표시합니다. 토스트가 사라지면 에러 내용을 다시 확인할 수 없기도 하고, 텍스트는 에러가 해결됐을 때 해당 에러 텍스트를 즉각적으로 없앨 수 있어 텍스트가 낫다고 판단했습니다.
제출 버튼을 항상 활성화시킵니다. 제출 버튼 클릭 시점에 에러가 있다면 에러 텍스트를 띄우고 제출을 막습니다. 
컴포넌트 표시 여부에 상관없이 필드 register가 되게하기위해 Form.HTML 내부에서 visible 유무를 처리합니다.
Note: 에러 메시지 디자인 필요
https://react-hook-form.com/docs/useform#mode
AboutEditor가 사용되는 소개탭 에디터에서 영어 본문이 없으면 제출이 불가해야합니다. 에디터 화면 진입 후 영어 본문 에디터가 표시되지 않았더라도 validation이 올바르게 이루어져야합니다.

✨ 영어 description 필수 처리, form 에러 표시 전략 수정

---

.github/workflows/playwright.yml
.github/workflows/random_reviewer.yaml

close #366 
최근 PR 목록을 가져온 뒤, 각각의 목록의 Reviewer들을 counts해 가장 적은 수의 사람을 선택합니다.
2명 이상일 경우 random으로 지정해요!

✨ 더 공평한 리뷰어 선정
