Dockerfile, apis/seminar.ts, app/community/seminar/[id]/page.tsx, next.config.js
- Dockerfile 추가 및 관련 next.js 설정
- linter 오류 임시 수정
=> 🐛 linter 오류 임시 제거

apis/auth.ts, components/layout/header/Header.tsx
- 백엔드에서 요청해서, 간단하게 헤더에 로그인, 로그아웃 버튼을 만들고  GET, POST 요청 각각 보내도록 만들었습니다.
- 특별한 내용은 없습니다!
=> ✨ 로그인, 로그아웃 테스트용 버튼 추가

apis/research.ts, app/about/directions/page.tsx, app/about/student-clubs/page.tsx, app/research/centers/page.tsx, app/research/groups/page.tsx, app/research/labs/[id]/page.tsx, app/research/labs/[name]/page.tsx, app/research/labs/page.tsx, components/common/selection/SelectionList.tsx, components/directions/LocationGuide.tsx, components/research/centers/ResearchCenterDetails.tsx, components/research/groups/ResearchGroupDetails.tsx, components/research/groups/ResearchGroupLabs.tsx, components/research/labs/ResearchLabDetails.tsx, components/research/labs/ResearchLabListRow.tsx, components/research/labs/ResesarchLabInfo.tsx, data/research.ts, types/page.ts, types/research.ts, utils/findSelectedItem.ts, utils/replaceCharacter.ts
- 연구 api 변동사항이 있어서 관련하여 리팩토링 진행했습니다.
- 연구실 개별 페이지 id 활용
- 교수 개별 페이지로 이동할 때도 id 활용
- 이에 맞춰 mock 데이터 수정
- 선택형 컴포넌트에서 존재하지 않는 쿼리 활용하는 상황 대응
=> ♻️ 연구 api 관련 리팩토링

.github/workflows/deploy.yaml, app/[locale]/academics/undergraduate/curriculum/page.tsx
- UndergradutecurriculumPage force static으로 변경
=> 🐛 전공 이수 표준 형태 배포 버전 버그 수정

app/[locale]/academics/undergraduate/course-changes/page.tsx, app/[locale]/research/centers/page.tsx, app/[locale]/research/groups/page.tsx, components/academics/CourseCard.tsx, components/common/selection/SelectionList.tsx, components/research/centers/ResearchCentersPageContent.tsx, components/research/groups/ResearchGroupsPageContent.tsx
- 배포 버전에서 선택형 클릭해도 바뀌지 않는 버그 임시 수정
- `searchParams`를 못 받아와서 문제가 발생했으므로 `useState` 사용해서 명시적으로 바꿔줌
- 추후에 api 연결하면 원상복구
=> 🐛연구 선택형 배포 버전 버그 수정

app/[locale]/academics/undergraduate/general-studies-requirements/page.tsx, app/[locale]/layout.tsx, app/[locale]/people/emeritus-faculty/[id]/page.tsx, app/[locale]/people/staff/[id]/page.tsx, app/[locale]/research/top-conference-list/page.tsx, components/academics/DegreeRequirements.tsx, components/admin/important/ImportantListRow.tsx, components/directions/LocationGuide.tsx, components/editor/common/BasicTextInput.tsx, components/editor/common/DateSelector.tsx, components/editor/common/FilePicker.tsx, components/editor/common/FilePickerRow.tsx, components/editor/common/ImagePicker.tsx, components/facilities/FacilitiesRow.tsx, components/layout/footer/Footer.tsx, components/people/PeopleInfoList.tsx, components/people/PeopleRow.tsx, components/research/groups/ResearchGroupsPageContent.tsx, components/research/labs/ResesarchLabInfo.tsx, styles/font.ts, tailwind.config.js
- 노토 400으로 되어 있던 곳을 노토 데미 라이트로 변경했습니다. 
- 폰트를 따로 설정하지 않았을 경우 데미라이트가 기본적으로 상속되도록 했습니다.
=> 💄 noto 400 -> noto demiLight

apis/index.ts, apis/main.ts, app/[locale]/page.tsx, components/main/ImportantPosts.tsx, components/main/NoticeListMain.tsx
=> ✨ 메인 네트워크 연결

components/layout/header/Header.tsx
=> ✨ 헤더 관리자 메뉴 추가

components/notice/NoticeListRow.tsx
=> 💄 공지 목록 row 배경색 변경

apis/admin.ts, apis/index.ts, app/[locale]/about/future-careers/page.tsx, app/[locale]/admin/page.tsx, app/[locale]/community/faculty-recruitment/page.tsx, app/[locale]/people/faculty/[id]/page.tsx, components/common/Tags.tsx, components/common/selection/SelectionList.tsx, components/directions/DirectionsDetails.tsx, components/facilities/FacilitiesRow.tsx, components/futureCareers/CareerStat.tsx, components/news/NewsRow.tsx, components/people/FacultyInfoWithImage.tsx, components/people/PeopleRow.tsx, components/studentClubs/ClubDetails.tsx
- 소개, 소식, 구성원 폰트 수정
- 관리자 페이지 네트워크 임시조치
=> 💄 폰트 일부 수정

app/[locale]/page.tsx, components/main/Notices.tsx, components/main/SlideGroups.tsx
- 메인 슬라이드 링크 우선순위 수정
- 메인 공지 더보기 버튼 태그 수정
=> 🐛 메인 버그 수정

app/[locale]/page.tsx, components/main/BgVideo.tsx, components/main/ImportantPosts.tsx, components/main/MainPageContent.tsx, components/main/Notices.tsx, components/main/SlideGroups.tsx, components/main/SlideScreen.tsx, package-lock.json, package.json
- 스크롤 유도 아이콘 추가
- react-intersection-observer 사용
- 메인 그래픽 위치 조정
=> ✨ 메인 페이지 스크롤 유도 아이콘 추가

apis/index.ts, app/[locale]/community/seminar/[id]/page.tsx, app/[locale]/layout.tsx, components/common/BetaBanner.tsx, components/editor/HTMLViewer.tsx, components/facilities/FacilitiesList.tsx, components/layout/header/Header.tsx, components/layout/navbar/Navbar.tsx, components/news/NewsRow.tsx, components/people/PeopleImageWithAnimation.tsx, components/seminar/SeminarRow.tsx
- layout.ts 리뷰 반영
- 몇몇 불필요한 image priority 제거
=> 💄 layout.ts 리뷰 반영

components/main/BgVideo.tsx, components/main/ImportantPosts.tsx, components/notice/NoticeListRow.tsx, components/research/labs/ResearchLabList.tsx, data/notice.ts
- 공지목록, 연구실 noto-demi 적용
- 메인 중요 안내 폰트 크기 조정
=> 💄 목록과 메인 글자 수정

components/layout/header/Header.tsx
=> 💄 헤더 pb 2rem

components/academics/CoursePageContent.tsx, components/research/centers/ResearchCentersPageContent.tsx, components/research/groups/ResearchGroupsPageContent.tsx
=> 💄 교과목 정보 width 조정

data/objects.ts
=> 🩹 이재욱 교수님 설명 업데이트

apis/index.ts, components/common/Dropdown.tsx, hooks/useOutClickAlerter.ts
모달 바깥 부분 클릭시 닫힘 기능 구현
참고 링크: https://stackoverflow.com/questions/32553158/detect-click-outside-react-component
=> ✨ 드롭다운 외부 클릭시 닫힘

.github/workflows/deploy.yaml, Dockerfile, app/[locale]/community/news/create/page.tsx, app/[locale]/layout.tsx, components/editor/common/SunEditorWrapper.tsx, components/layout/header/Header.tsx, next.config.mjs
- http://52.78.126.205:3000/
- 에러가 넘 많아 빌드 중에는 eslint를 끕니다😢
=> 🚀 EC2 자동 배포

components/academics/RoadMapModal.tsx, components/research/labs/ResearchLabList.tsx, components/research/labs/ResearchLabListHeader.tsx, components/research/labs/ResearchLabListRow.tsx
- 연구실 목록 디자인 수정
- 로드맵 이미지 크기 조정
- 모달 안에 너비가 꽉 차도록 하려고 했으나, 모달 최대 높이가 정해져 있기 때문에 불가함. 혹은 비율이 깨짐. 이전보다는 키워두었음.
=> 💄 연구실 목록 디자인 수정

app/[locale]/community/news/NewsPageContent.tsx, app/[locale]/community/notice/NoticeListHeader.tsx, app/[locale]/community/notice/NoticeListRow.tsx, app/[locale]/community/notice/NoticePageContent.tsx, app/[locale]/community/seminar/SeminarPageContent.tsx, components/common/Pagination.tsx, utils/hooks/useResponsive.ts
- 페이지네이션바에서 보여주는 숫자를 모바일에서는 5까지, 데스크탑에서는 10까지로 변경
- 공지 목록 웹버전 반응형 버그 수정
=> ♻️ 스크린 크기에 따라 페이지네이션 숫자 개수 변경

app/[locale]/community/news/[id]/page.tsx, app/[locale]/community/notice/[id]/page.tsx, app/[locale]/community/seminar/[id]/page.tsx, components/common/Attachments.tsx, components/common/selection/SelectionList.tsx, package-lock.json
- 공지사항/새소식/세미나 상세 페이지 모바일 반응형 작업
=> 📱 소식탭 본문 모바일 반응형 추가

app/[locale]/community/news/NewsPageContent.tsx
- 웹 버전 새소식 목록 양옆 마진 10px -> 40px
=> 💄 새소식 목록 양옆 마진 수정

app/[locale]/about/future-careers/CareerStat.tsx, app/[locale]/about/future-careers/page.tsx
- 소개 - 졸업생 창업기업 표 웹/모바일 반응형 추가
=> 📱 졸업생 창업 기업 반응형

.github/workflows/deploy.yaml, Dockerfile, actions/session.ts, apis/index.ts, app/[locale]/community/news/[id]/page.tsx, app/[locale]/community/news/page.tsx, app/[locale]/community/notice/page.tsx, app/[locale]/community/seminar/page.tsx, next.config.mjs, package.json
- package.json에서 dependencies에는 빌드에 필요한 것들, devDependencies에는 필요하지 않은 것을 배치했습니다. 
- Dockerfile을 수정해 빌드시 dependencies만 설치합니다. 
- 이전 PR의 fetchWithRetry의 횟수를 늘리고 누락된 await을 추가했습니다.
=> ✨ 빌드시 devDependency를 설치하지 않음

.github/workflows/deploy.yaml, app/[locale]/people/helper/PeopleCell.tsx, app/[locale]/reservations/[roomType]/[roomName]/helper/calendar/CalendarContent.tsx, app/[locale]/search/AboutSection.tsx, app/[locale]/search/AcademicSection.tsx, app/[locale]/search/AdmissionSection.tsx, app/[locale]/search/CommunitySection.tsx, app/[locale]/search/MemberSection.tsx, app/[locale]/search/ResearchSection.tsx, app/[locale]/search/helper/BasicRow.tsx, app/[locale]/search/helper/CircleTitle.tsx, app/[locale]/search/helper/Divider.tsx, app/[locale]/search/helper/NoticeRow.tsx, app/[locale]/search/helper/OrangeCircle.tsx, app/[locale]/search/helper/Section.tsx, app/[locale]/search/page.tsx, components/common/ImageWithFallback.tsx, components/common/RangeBolded.tsx, components/layout/header/HeaderSearchBar.tsx, constants/tag.ts, types/search.ts
- 검색 api 반영
- /search 디자인 수정사항 반영
- PeopleCell image flickering 제거
=> 💄 /search 디자인 적용

components/modal/CserealModal.tsx
=> 💄 시리얼 모달 크기 반응형 조절

app/[locale]/[...rest]/page.tsx, app/[locale]/not-found.tsx
=> ✨ 404 페이지 추가

app/[locale]/page.tsx, components/main/NoticeSection.tsx
=> 📱 메인 공지사항 반응형

app/[locale]/academics/graduate/course-changes/page.tsx, app/[locale]/academics/graduate/courses/CoursePageContent.tsx, app/[locale]/academics/helper/CourseChanges.tsx, app/[locale]/academics/helper/TimeLine.tsx, app/[locale]/academics/undergraduate/course-changes/page.tsx, app/[locale]/academics/undergraduate/courses/CoursePageContent.tsx, app/[locale]/research/labs/[id]/ResearchLabDetailContent.tsx, app/[locale]/reservations/[roomType]/[roomName]/helper/calendar/CalendarContent.tsx, app/[locale]/reservations/[roomType]/[roomName]/helper/useResponsiveRow.tsx, components/common/Pagination.tsx, components/editor/TopRightImageContent.tsx, components/main/NoticeSection.tsx, contexts/NavbarContext.tsx, utils/hooks/useResponsive.ts
- 화면 너비 좁아지면 2줄로 변경
- `useResponsive` `screenType` 없애고 `isMovbile`, `isDektopWide` 등으로 변경
=> 📱 교과목 변경내역 타임라인 반응형

utils/hooks/useResponsive.ts
-  useResponsive isMobile 반대로 된 버그 수정
=> 🐛 useResponsive isMobile 반대로 된 버그 수정

app/[locale]/page.tsx, components/main/NewsCard.tsx, components/main/NewsCarousel.tsx, components/main/NewsCarouselMobile.tsx, components/main/NewsSection.tsx, utils/hooks/useResponsive.ts
- 메인 새소식 캐러셀 모바일 버전 추가
- `useResponsive` 화면 크기 옵션 추가
=> 📱 메인 새소식 캐러셀 모바일

app/[locale]/people/emeritus-faculty/[id]/page.tsx, app/[locale]/people/faculty/[id]/page.tsx, app/[locale]/people/helper/Profile.tsx, app/[locale]/people/staff/[id]/page.tsx
- 교수진 개별 페이지 모바일 추가
- 역대 교수진/행정직원 개별 페이지 레이아웃 수정
- 역대 교수진/행정직원 개별 페이지 모바일 추가
=> 📱 구성원 모바일 추가

app/[locale]/reservations/[roomType]/[roomName]/helper/ReservationCalendar.tsx, app/[locale]/reservations/[roomType]/[roomName]/helper/calendar/CalendarContent.tsx
=> 🐛 캘린더 서브내비 겹치는 현상 수정

app/[locale]/page.tsx
=> 🐛 메인 바로가기 장학 링크 수정

components/common/Pagination.tsx
=> 🐛 모바일 페이지네이션 개수 수정

app/[locale]/academics/helper/courses/CourseList.tsx, app/[locale]/academics/helper/courses/CourseListHeader.tsx, app/[locale]/academics/helper/courses/CourseListRow.tsx
=> 📱 교과과정 표 모바일

app/[locale]/research/top-conference-list/ConferenceListTable.tsx, components/main/GraphicSection.tsx, types/research.ts
- 교수님 미팅에서 필요없다고 하셔서 뺐습니다
- 메인 글귀에 띄어쓰기 추가했습니다
=> ✨ TCL에서 ack 제거

package-lock.json, package.json
SSRF 취약점 대응
참고: https://www.assetnote.io/resources/research/digging-for-ssrf-in-nextjs-apps
=> Next 버전 업데이트

app/[locale]/academics/page.tsx, app/[locale]/academics/undergraduate/course-changes/page.tsx, app/[locale]/academics/undergraduate/courses/page.tsx, app/[locale]/academics/undergraduate/curriculum/page.tsx, app/[locale]/academics/undergraduate/degree-requirements/page.tsx, app/[locale]/academics/undergraduate/general-studies-requirements/page.tsx, app/[locale]/academics/undergraduate/guide/page.tsx, app/[locale]/academics/undergraduate/scholarship/page.tsx, app/[locale]/people/page.tsx
- 구성원 대분류 페이지 설명 삭제
- 메타데이터 불필요한 코드 일부 간소화
=> 🩹 구성원 설명 삭제

constants/tag.ts
- 공지 태그 foreign -> international
- 데브에 먼저 배포 후 백엔드 작업 완료되면 프로드에 마저 배포 예정
=> 🩹공지 태그 foreign -> international

app/.internal/page.tsx
=> 🩹 메일링 리스트 항목 추가

app/[locale]/people/staff/[id]/page.tsx, app/[locale]/people/staff/page.tsx
참고 문서: https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag?hl=ko
=> ✨ 몇몇 사진 크롤링 방지

app/[locale]/people/helper/PeopleCell.tsx
- 줄바꿈이 안 되어서 깨졌던 거라 `flex-wrap` 속성 추가
=> 💄 구성원 academic rank 정렬 깨짐 수정

apis/common.ts, app/.internal/InternalContent.tsx, app/.internal/page.tsx, tsconfig.json
- 프론트 재배포 해야 할 것 같은데 아직 서버에서 인터널 프로드 배포가 안 되어서 프론트도 배포가 불가함... 따라서 인터널 api 썼던 부분 주석처리하고 목데이터 다시 넣어둠
- 시간 없어서 주석으로 다 처리
- 추후 서버 배포되면 돌려놓을 예정
=> 🐛 인터널 편집 주석 처리

app/[locale]/about/contact/page.tsx, app/[locale]/about/directions/page.tsx, app/[locale]/about/facilities/page.tsx, app/[locale]/about/future-careers/page.tsx, app/[locale]/about/greetings/page.tsx, app/[locale]/about/history/page.tsx, app/[locale]/about/overview/page.tsx, app/[locale]/about/page.tsx, app/[locale]/about/student-clubs/page.tsx, constants/audit.ts
- '캐시화 가능한 SSL 페이지 발견'이 해결될까싶어 /about 쪽 페이지들을 임시로 force-dynamic 처리
- 내일 테스트를 위한 404 페이지 제거
=> 🔒️ 일부 페이지 force-dynamic 처리

app/[locale]/academics/undergraduate/courses/CoursePageContent.tsx, app/[locale]/academics/undergraduate/courses/page.tsx, app/[locale]/academics/undergraduate/curriculum/CurriculumBody.tsx, app/[locale]/academics/undergraduate/curriculum/page.tsx
- 로드맵 내용 업데이트되기 전까지 임시로 버튼 제거 및 그에 따른 스타일 미세 수정
=> 🩹 로드맵 버튼 임시 제거

app/[locale]/academics/graduate/courses/CoursePageContent.tsx, app/[locale]/academics/helper/courses/CourseList.tsx, app/[locale]/academics/helper/courses/CourseToolbar.tsx, app/[locale]/academics/helper/courses/useCourseToolbar.tsx, app/[locale]/academics/undergraduate/courses/CoursePageContent.tsx, app/[locale]/academics/undergraduate/courses/page.tsx
- 기본 상태 `목록형`으로 설정
- 선택된 정렬 옵션 이후에는 가나다순으로 마저 정렬
- 카드형/목록형 정렬 로직 통합
=> 🐛 교과과정 정렬 수정

app/[locale]/academics/graduate/course-changes/page.tsx, app/[locale]/academics/helper/CourseChanges.tsx, app/[locale]/academics/helper/TimeLine.tsx, app/[locale]/academics/undergraduate/course-changes/page.tsx
- 연도 하드코딩 없애고 데이터에 따라 유동적으로 타임라인 생성하도록 변경
- 마지막 타임은 여러 연도 토글로 보여주도록 수정
- 토글 디자인 나중에 확정되면 따로 수정할 예정
- 반응형 하드코딩 없애고 자동화
=> ♻️ 타임라인 리팩토링

apis/common.ts, apis/index.ts, app/[locale]/community/news/[id]/page.tsx, app/[locale]/community/notice/[id]/page.tsx, app/[locale]/community/seminar/[id]/page.tsx, components/post/InvalidIDFallback.tsx
- metadata와 server component 본문에 있는 fetch 주변을 try-catch로 감쌌습니다.
=> 🐛 소식탭 게시물 상세에서 500이 뜨는 문제 해결

app/[locale]/community/notice/page.tsx
=> 🐛 validate 오류 수정

utils/validateSearchParams.ts
=> 🐛 정수 overflow 수정

app/[locale]/academics/helper/CourseChanges.tsx, app/[locale]/academics/helper/TimeLine.tsx, app/[locale]/academics/undergraduate/courses/CoursePageContent.tsx, tailwind.config.js
- 교과과정 https://github.com/wafflestudio/csereal-web/pull/240
- 타임라인 https://github.com/wafflestudio/csereal-web/pull/241
=> ♻️ 타임라인과 교과과정 리뷰 반영

components/layout/footer/Footer.tsx
=> 💄 영어 푸터 너비 조정

app/[locale]/community/notice/create/page.tsx
=> 🩹 불필요한 구문 삭제

apis/academics.ts, app/.internal/InternalContent.tsx, app/[locale]/academics/helper/courses/CourseDetailModal.tsx, app/[locale]/academics/helper/guide/GuideEditPageContent.tsx, app/[locale]/academics/helper/timeline/TimelineEditor.tsx, app/[locale]/academics/helper/timeline/TimelineViewer.tsx, app/[locale]/academics/undergraduate/degree-requirements/edit/DegreeRequirementsEditPageContent.tsx, app/[locale]/people/emeritus-faculty/[id]/EmeritusFacultyMemberPageContent.tsx, app/[locale]/people/faculty/[id]/FacultyMemberPageContent.tsx, app/[locale]/people/faculty/[id]/edit/FacultyEditPageContent.tsx, app/[locale]/people/staff/[id]/StaffMemberPageContent.tsx, app/[locale]/people/staff/[id]/edit/StaffEditPageContent.tsx, app/[locale]/people/staff/create/page.tsx, app/[locale]/research/labs/[id]/ResearchLabDetailContent.tsx, components/common/Attachments.tsx, types/research.ts
- 에러 객체 참고해서 에러 메시지 띄우도록 수정
- 필수교양과목 delete api url 수정
- 첨부파일명 디코딩해서 보여주도록 수정
- 연구실 객체 타입 변경사항 반영 (서버측에서 그룹 id도 같이 내려주도록 변경됨)
=> 🐛 학사 및 교과 api url 수정 및 첨부파일 디코딩

app/[locale]/academics/undergraduate/general-studies-requirements/create/page.tsx, app/[locale]/academics/undergraduate/general-studies-requirements/edit/GeneralStudiesEditPageContent.tsx
- 필교에 교과과정 api를 전달하고 있었던 오류 수정했습니다.
=> 🐛 필수교양과목 api 전달 오류 수정

README.md, actions/session.ts, apis/v1/mock-login.ts, apis/v1/user/is-staff.ts, app/.internal/InternalContent.tsx, app/.internal/layout.tsx, app/[locale]/layout.tsx, contexts/SessionContext.tsx, package-lock.json, package.json
SessionContext 리팩토링
- SessionContext의 api 요청 코드를 api 폴더로 이동
- 리드미에 phase 관련 내용 보충
- SessionContextProvider의 next-intl 의존성 제거
.
.
=> ♻️ SessionContext 리팩토링

app/[locale]/layout.tsx, components/layout/header/Header.tsx, components/layout/header/HeaderRight.tsx, components/layout/navbar/MobileNav.tsx, constants/env.ts, constants/network.ts, contexts/SessionContext.tsx, middleware.ts, server.mjs
- top 속성이 height로 적용된 부분 수정
- BASE_URL이 클라단에서 접근이 안되는 문제 수정(NEXT_PUBLIC...로 rename)
- isDev의 사용 제거. isProd, isBeta, isLocal로 대체
=> 🐛 헤더 푸터 네비 검수

middleware.ts
CSP img-src에 시리얼 prod, dev 서버를 추가합니다.
선에디터에서 이미지를 추가했을 때 잘 표시돼야합니다.
=> 🐛 CSP image-src에 시리얼 서버 추가

app/[locale]/search/fetchContent.ts
=> 🐛 simple-import-sort 실행

app/[locale]/search/fetchContent.ts
=> 🚑️ 잘못된 import 수정

.github/workflows/playwright.yml, .gitignore, package-lock.json, package.json, playwright.config.ts, tests/example.spec.ts
- playwright 설치
- PR이 올라왔을 때/푸시됐을 때 테스트를 실행
- 일단 크로미움 브라우저 대상으로만 돌립니다. 
- 테스트 실패시 머지를 막도록 처리할 예정입니다. 
이 PR 머지한 뒤로 올라온 PR들에 테스트 결과가 떠야함
https://playwright.dev/docs/ci#github-actions
=> 👷 playwright 적용

app/[locale]/community/council/meeting-minute/create/client.tsx, app/[locale]/community/council/meeting-minute/create/page.tsx
=> 🚑️ 잘못된 searchParam 타입 수정

app/[locale]/community/council/components/CouncilAttachments.tsx, components/common/Attachments.tsx, components/layout/navbar/NavbarDetail.tsx, components/layout/pageLayout/SubNavbar.tsx, constants/segmentNode.ts, utils/format.ts
- 메인네비에서 학생회 숨김
- 섭네비에서 학생회 표시
- 파일 사이즈 표시 에러 수정
=> 🐛 학생회 QA 반영

app/[locale]/community/council/components/CouncilAttachments.tsx, app/[locale]/community/council/meeting-minute/MinutePageContent.tsx, components/common/Attachments.tsx, components/form/File.tsx, constants/segmentNode.ts
=> 🐛 학생회 첨부파일 반응형

app/[locale]/people/faculty/[id]/page.tsx
- 교수진 개별 페이지 faculty status 예외처리에서 객원교수일 경우가 누락되어있던 버그 수정
=> 🐛 교수진 개별 페이지 예외처리 버그 수정

app/[locale]/reservations/[roomType]/[roomName]/helper/calendar/CalendarColumn.tsx
async가 붙어 서버 컴포넌트가 된 클라 컴포넌트를 수정합니다. 지금까지 왜 됐지...?
아래 에러를 수정합니다. 
예약 페이지에서 위 에러가 표시되면 안됩니다.
=> 🐛 불필요한 async 제거

.github/workflows/random_reviewer.yaml, reviewer.json
PR이 열리면 랜덤한 리뷰어를 설정합니다. 
~~PR들에 자동으로 랜덤 리뷰어가 지정되는지 확인~~ 확인 완료
https://bluemiv.tistory.com/122
=> 👷 랜덤 리뷰어 설정 

apis/v2/staff/[id_ko]/id_en.ts, app/[locale]/admin/helper/slide/SlideList.tsx
=> 🐛 staff api 오타 수정

app/[locale]/error.tsx
close #333
Error 페이지를 친절하게 수정했습니다.
처음에는 아스키 아트로 귀엽게 표현해보면 어떤가 싶은데 아무래도 공식 홈페이지라... 우선은 차분한 메시지로 작성했어요.
ex)
```
_________________________
|                         |
|        ERROR !!!        |
|                         |
|         X _ X           |
|                         |
|_________________________|
__|__|__
/         \
/___________)
```
추가로 에러 페이지에 필요 없기도 하고, 특히 상위 페이지에서 에러날 경우 SubNavbar가 너무 지저분해서 숨김으로 바꿨습니다.
백엔드 서버를 실행시키지 않고 beta를 로컬에서 돌리면 에러 페이지가 나타납니다.
=> 💄 에러 페이지 친절하게 수정하기
